# Config

language: c
sudo: false
dist: trusty
cache: bundler

# Build matrix (2x compiler, 1x confopts)
compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - uuid-dev
      - libelf-dev
      - krb5-multidev
      - heimdal-multidev
      - libcrack2-dev
      - libsasl2-dev
      - libperl-dev
      - libtool
      - libltdl-dev
      - binutils-dev
      - libssl-dev
      - libgnutls-dev
      - libwrap0-dev
#      - libiodbc2-dev
      - unixodbc-dev
      - libslp-dev
#      - libsodium-dev
      - bc

script:
  - ./configure
      --enable-overlays --enable-contrib --enable-check
      --enable-dynacl --enable-aci --enable-crypt --enable-lmpasswd --enable-spasswd
      --enable-slapi --enable-rlookups --enable-slp --enable-wrappers
      --enable-backends --disable-bdb --disable-hdb --disable-ndb
  - make dist
  - make && SKIPLONG=yes make test
