# Config

language: c
sudo: false
dist: trusty
cache: bundler

# Build matrix (2x compiler, 1x confopts)
compiler:
  - gcc
  - clang

env:
  - LIBTOOL_SUPPRESS_DEFAULT=no

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - uuid-dev
      - libelf-dev
      - krb5-multidev
      - heimdal-multidev
      - libcrack2-dev
      - libsasl2-dev
      - libperl-dev
      - libtool
      - libltdl-dev
      - binutils-dev
      - libssl-dev
      - libgnutls-dev
      - libwrap0-dev
#      - libiodbc2-dev
      - unixodbc-dev
      - libslp-dev
#      - libsodium-dev
      - libdb-dev
      - bc
      - gdb

script:
  - ./bootstrap.sh
  - ./configure CFLAGS="-Ofast -ggdb3 -gdwarf-4" --prefix=$(pwd)/_install
      --enable-check=always --enable-hipagut=always --enable-debug --disable-syslog
      --enable-overlays --enable-contrib --enable-maintainer-mode
      --enable-dynacl --enable-aci --enable-crypt --enable-lmpasswd --enable-spasswd
      --enable-slapi --enable-rlookups --enable-slp --enable-wrappers
      --enable-backends --disable-bdb --disable-hdb --disable-ndb
  - make dist
  - mkdir dist && (cd dist
      && tar --strip-component=1 xaf ../*.tar.*
      && ./configure CFLAGS=-Os EXTRA_CFLAGS="-Wall -Werror"
        --enable-overlays=mod --enable-contrib --enable-experimental --enable-debug
        --enable-dynacl --enable-aci --enable-crypt --enable-lmpasswd --enable-spasswd
        --enable-slapi --enable-rlookups --enable-slp --enable-wrappers
        --enable-backends=mod --disable-ndb --disable-dependency-tracking
      && make CFLAGS="-Os -Wall -Werror"
      && make install)
  - make EXTRA_CFLAGS="-Wall -Werror" && make install
  - ulimit -c unlimited && SKIPLONG=yes make test
